const { AssignmentReturnedTwoTone } = require("@mui/icons-material");
const https = require("https");

const cities_all = [
  "Allendorf (Lumda), Hessen, Germany",
  "Eltville am Rhein, Hessen, Germany",
  "Hadamar, Hessen, Germany",
  "Lampertheim, Hessen, Germany",
  "Ober-Ramstadt, Hessen, Germany",
  "Seligenstadt, Hessen, Germany",
  "Alsfeld, Hessen, Germany",
  "Eppstein, Hessen, Germany",
  "Haiger, Hessen, Germany",
  "Langen, Hessen, Germany",
  "Obertshausen, Hessen, Germany",
  "Solms, Hessen, Germany",
  "Amöneburg, Hessen, Germany",
  "Erbach, Hessen, Germany",
  "Hanau, Hessen, Germany",
  "Langenselbold, Hessen, Germany",
  "Oberursel (Taunus), Hessen, Germany",
  "Sontra, Hessen, Germany",
  "Aßlar, Hessen, Germany",
  "Erlensee, Hessen, Germany",
  "Hattersheim am Main, Hessen, Germany",
  "Laubach, Hessen, Germany",
  "Oberzent, Hessen, Germany",
  "Spangenberg, Hessen, Germany",
  "Eschborn, Hessen, Germany",
  "Hatzfeld (Eder), Hessen, Germany",
  "Lauterbach (Hessen), Hessen, Germany",
  "Oestrich-Winkel, Hessen, Germany",
  "Stadtallendorf, Hessen, Germany",
  "Eschwege, Hessen, Germany",
  "Heppenheim (Bergstraße), Hessen, Germany",
  "Leun, Hessen, Germany",
  "Offenbach am Main, Hessen, Germany",
  "Staufenberg, Hessen, Germany",
  "Babenhausen, Hessen, Germany",
  "Herborn, Hessen, Germany",
  "Lich, Hessen, Germany",
  "Ortenberg, Hessen, Germany",
  "Steinau an der Straße, Hessen, Germany",
  "Bad Arolsen, Hessen, Germany",
  "Herbstein, Hessen, Germany",
  "Lichtenfels, Hessen, Germany",
  "Steinbach (Taunus), Hessen, Germany",
  "Bad Camberg, Hessen, Germany",
  "Felsberg, Hessen, Germany",
  "Heringen (Werra), Hessen, Germany",
  "Liebenau, Hessen, Germany",
  "Bad Hersfeld, Hessen, Germany",
  "Flörsheim am Main, Hessen, Germany",
  "Hessisch, Hessen, Germany",
  "Lichtenau, Hessen, Germany",
  "Limburg a.d. Lahn, Hessen, Germany",
  "Pfungstadt, Hessen, Germany",
  "Bad Homburg v.d. Höhe, Hessen, Germany",
  "Florstadt, Hessen, Germany",
  "Heusenstamm, Hessen, Germany",
  "Linden, Hessen, Germany",
  "Pohlheim, Hessen, Germany",
  "Tann (Rhön), Hessen, Germany",
  "Bad Karlshafen, Hessen, Germany",
  "Frankenau, Hessen, Germany",
  "Hirschhorn (Neckar), Hessen, Germany",
  "Lindenfels, Hessen, Germany",
  "Taunusstein, Hessen, Germany",
  "Bad König, Hessen, Germany",
  "Frankenberg (Eder), Hessen, Germany",
  "Hochheim am Main, Hessen, Germany",
  "Lollar, Hessen, Germany",
  "Trendelburg, Hessen, Germany",
  "Bad Nauheim, Hessen, Germany",
  "Frankfurt am Main, Hessen, Germany",
  "Hofgeismar, Hessen, Germany",
  "Lorch, Hessen, Germany",
  "Raunheim, Hessen, Germany",
  "Bad Orb, Hessen, Germany",
  "Friedberg (Hessen), Hessen, Germany",
  "Hofheim am Taunus, Hessen, Germany",
  "Lorsch, Hessen, Germany",
  "Rauschenberg, Hessen, Germany",
  "Bad Schwalbach, Hessen, Germany",
  "Friedrichsdorf, Hessen, Germany",
  "Homberg (Efze), Hessen, Germany",
  "Reichelsheim (Wetterau), Hessen, Germany",
  "Ulrichstein, Hessen, Germany",
  "Bad Soden am Taunus, Hessen, Germany",
  "Fritzlar, Hessen, Germany",
  "Homberg (Ohm), Hessen, Germany",
  "Reinheim, Hessen, Germany",
  "Usingen, Hessen, Germany",
  "Bad Soden-Salmünster, Hessen, Germany",
  "Fulda, Hessen, Germany",
  "Hünfeld, Hessen, Germany",
  "Maintal, Hessen, Germany",
  "Riedstadt, Hessen, Germany",
  "Bad Sooden-Allendorf, Hessen, Germany",
  "Hungen, Hessen, Germany",
  "Marburg, Hessen, Germany",
  "Rodgau, Hessen, Germany",
  "Bad Vilbel, Hessen, Germany",
  "Melsungen, Hessen, Germany",
  "Rödermark, Hessen, Germany",
  "Vellmar, Hessen, Germany",
  "Bad Wildungen, Hessen, Germany",
  "Michelstadt, Hessen, Germany",
  "Romrod, Hessen, Germany",
  "Viernheim, Hessen, Germany",
  "Battenberg (Eder), Hessen, Germany",
  "Gedern, Hessen, Germany",
  "Idstein, Hessen, Germany",
  "Mörfelden-Walldorf, Hessen, Germany",
  "Rosbach v.d. Höhe, Hessen, Germany",
  "Volkmarsen, Hessen, Germany",
  "Baunatal, Hessen, Germany",
  "Geisenheim, Hessen, Germany",
  "Immenhausen, Hessen, Germany",
  "Mühlheim am Main, Hessen, Germany",
  "Rosenthal, Hessen, Germany",
  "Bebra, Hessen, Germany",
  "Gelnhausen, Hessen, Germany",
  "Münzenberg, Hessen, Germany",
  "Rotenburg a.d. Fulda, Hessen, Germany",
  "Bensheim, Hessen, Germany",
  "Gemünden (Wohra), Hessen, Germany",
  "Rüdesheim am Rhein, Hessen, Germany",
  "Wächtersbach, Hessen, Germany",
  "Biedenkopf, Hessen, Germany",
  "Gernsheim, Hessen, Germany",
  "Karben, Hessen, Germany",
  "Rüsselsheim, Hessen, Germany",
  "Waldeck, Hessen, Germany",
  "Borken (Hessen), Hessen, Germany",
  "Gersfeld (Rhön), Hessen, Germany",
  "Kassel, Hessen, Germany",
  "Naumburg, Hessen, Germany",
  "Runkel, Hessen, Germany",
  "Waldkappel, Hessen, Germany",
  "Braunfels, Hessen, Germany",
  "Gießen, Hessen, Germany",
  "Kelkheim (Taunus), Hessen, Germany",
  "Neckarsteinach, Hessen, Germany",
  "Wanfried, Hessen, Germany",
  "Breuberg, Hessen, Germany",
  "Ginsheim-Gustavsburg, Hessen, Germany",
  "Kelsterbach, Hessen, Germany",
  "Neu-Anspach, Hessen, Germany",
  "Weilburg, Hessen, Germany",
  "Bruchköbel, Hessen, Germany",
  "Gladenbach, Hessen, Germany",
  "Kirchhain, Hessen, Germany",
  "Neu-Isenburg, Hessen, Germany",
  "Schlitz, Hessen, Germany",
  "Weiterstadt, Hessen, Germany",
  "Büdingen, Hessen, Germany",
  "Grebenau, Hessen, Germany",
  "Kirtorf, Hessen, Germany",
  "Neukirchen, Hessen, Germany",
  "Schlüchtern, Hessen, Germany",
  "Wetter (Hessen), Hessen, Germany",
  "Bürstadt, Hessen, Germany",
  "Grebenstein, Hessen, Germany",
  "Königstein im Taunus, Hessen, Germany",
  "Neustadt (Hessen), Hessen, Germany",
  "Schotten, Hessen, Germany",
  "Wetzlar, Hessen, Germany",
  "Butzbach, Hessen, Germany",
  "Griesheim, Hessen, Germany",
  "Korbach, Hessen, Germany",
  "Nidda, Hessen, Germany",
  "Schwalbach am Taunus, Hessen, Germany",
  "Wiesbaden, Hessen, Germany",
  "Großalmerode, Hessen, Germany",
  "Kronberg im Taunus, Hessen, Germany",
  "Niddatal, Hessen, Germany",
  "Schwalmstadt, Hessen, Germany",
  "Witzenhausen, Hessen, Germany",
  "Groß-Bieberau, Hessen, Germany",
  "Nidderau, Hessen, Germany",
  "Schwarzenborn, Hessen, Germany",
  "Wolfhagen, Hessen, Germany",
  "Darmstadt, Hessen, Germany",
  "Groß-Gerau, Hessen, Germany",
  "Niedenstein, Hessen, Germany",
  "Dieburg, Hessen, Germany",
  "Groß-Umstadt, Hessen, Germany",
  "Diemelstadt, Hessen, Germany",
  "Grünberg, Hessen, Germany",
  "Zierenberg, Hessen, Germany",
  "Dietzenbach, Hessen, Germany",
  "Gudensberg, Hessen, Germany",
  "Zwingenberg, Hessen, Germany",
  "Dillenburg, Hessen, Germany",
  "Dreieich, Hessen, Germany",
];

const cities = [
  "Herbstein, Hessen, Germany",
  "Bad Arolsen, Hessen, Germany",
  "Steinau an der Straße, Hessen, Germany",
  "Bad Camberg, Hessen, Germany",
  "Hochheim am Main, Hessen, Germany",
  "Taunusstein, Hessen, Germany",
  "Steinbach (Taunus), Hessen, Germany",
  "Frankfurt am Main, Hessen, Germany",
  "Bad Nauheim, Hessen, Germany",
  "Bad König, Hessen, Germany",
  "Flörsheim am Main, Hessen, Germany",
  "Lichtenau, Hessen, Germany",
  "Bad Wildungen, Hessen, Germany",
  "Usingen, Hessen, Germany",
  "Reinheim, Hessen, Germany",
  "Geisenheim, Hessen, Germany",
  "Hungen, Hessen, Germany",
  "Herborn, Hessen, Germany",
  "Ulrichstein, Hessen, Germany",
  "Lich, Hessen, Germany",
  "Bad Soden am Taunus, Hessen, Germany",
  "Rauschenberg, Hessen, Germany",
  "Rüdesheim am Rhein, Hessen, Germany",
  "Schlitz, Hessen, Germany",
  "Gladenbach, Hessen, Germany",
  "Neu-Isenburg, Hessen, Germany",
  "Schwarzenborn, Hessen, Germany",
  "Kronberg im Taunus, Hessen, Germany",
  "Kelsterbach, Hessen, Germany",
  "Büdingen, Hessen, Germany",
  "Groß-Gerau, Hessen, Germany",
  "Bruchköbel, Hessen, Germany",
  "Grebenstein, Hessen, Germany",
  "Dietzenbach, Hessen, Germany",
  "Dillenburg, Hessen, Germany",
  "Darmstadt, Hessen, Germany",
  "Niddatal, Hessen, Germany",
  "Fritzlar, Hessen, Germany",
  "Hünfeld, Hessen, Germany",
  "Raunheim, Hessen, Germany",
  "Homberg (Efze), Hessen, Germany",
  "Waldkappel, Hessen, Germany",
  "Naumburg, Hessen, Germany",
  "Waldeck, Hessen, Germany",
  "Friedrichsdorf, Hessen, Germany",
  "Butzbach, Hessen, Germany",
];

async function run() {
  // Change it here
  const localisedCities = [];
  await cities.map((c) => {
    console.log("Parsing city ", c);
    var waitTill = new Date(new Date().getTime() + 1 * 100); //sorry for this
    while (waitTill > new Date()) {}
    const apikey = process.argv[2];
    const options = {
      hostname: "maps.googleapis.com",
      port: 443,
      path: encodeURI("/maps/api/geocode/json?key=" + apikey + "&address=" + c),
      method: "GET",
    };

    const req = https
      .get(options, (res) => {
        var body = "";

        res.on("data", function (chunk) {
          body += chunk;
        });

        res.on("end", function () {
          var response = JSON.parse(body);
          //console.log("Response from google", response);
          if (response["results"].length > 0) {
            const coordinates = response["results"][0]["geometry"]["location"];
            console.log("Got a response: ", c, coordinates);
            localisedCities.push({
              city: c,
              lat: coordinates.lat,
              lng: coordinates.lng,
            });
          } else {
            console.log("Limit breached:", c);
          }
        });
      })
      .on("error", function (e) {
        console.log("Got an error: ", e);
      });
  });
  console.log("New JSON:", localisedCities);
}

run();
